version: "2"
linters:
  default: all
  disable:
    - arangolint
    - ginkgolinter
    - promlinter
    - protogetter
    - spancheck
    - zerologlint
    - sloglint
    - goheader
    - gomodguard
    - depguard
    - forbidigo
    - wsl
    - copyloopvar
    - varnamelen
    - testpackage
    - inamedparam
    - noinlineerr
    - nonamedreturns
  settings:
    wsl_v5:
      allow-whole-block: false
      disable:
        - assign
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        source: "^//go:generate "
      - linters:
          - lll
        source: (?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\(\)\*\+,;=.]+
      - linters:
          - lll
        source: "// ?TODO "
      - linters:
          - wsl_v5
        path: _test\.go
        text: only cuddled expressions if assigning variable or using from line above
      - linters:
          - wsl_v5
        path: _test\.go
        text: assignments should only be cuddled with other assignments
      - linters:
          - wsl_v5
        path: _test\.go
        text: missing whitespace above this line
      - linters:
          - revive
        path: _test\.go
        text: seems to be unused, consider removing or renaming it as _
      - linters:
          - revive
        path: _test\.go
        text: "context-keys-type: should not use basic type string as key in context.WithValue"
      - linters:
          - revive
        path: _test\.go
        text: "context-keys-type: should not use basic type untyped string as key in context.WithValue"
      - linters:
          - staticcheck
        path: _test\.go
        text: "SA1029: should not use built-in type string as key for value; define your own type to avoid collisions"
      - linters:
          - ireturn
        path: (.+/)?context\.go
      - linters:
          - ireturn
        path: (.+/)?transaction\.go
        source: \) Begin\(ctx
      - linters:
          - ireturn
        path: (.+/)?settings\.go
        source: (?:EnrichBy|SetPropagation|SetCtxKey|CtxKey|SetCancelable|SetTimeout)
      - linters:
          - gochecknoglobals
        source: DefaultCtxGetter
      - &internal_path
        path: (^trm/internal|^internal)
        text: "var-naming: avoid package names that conflict with Go standard library package names"
      - <<: *internal_path
        text: "var-naming: don't use an underscore in package name"
      - <<: *internal_path
        text: "package-comments: should have a package comment"
      - <<: *internal_path
        text: "ST1003: should not use underscores in package names"
      - linters:
          - containedctx
          - err113
          - errcheck
          - exhaustruct
          - forcetypeassert
          - funlen
          - gochecknoglobals
          - goconst
          - mnd
          - nolintlint
        path: (_test\.go|^trm/internal|^internal)
      - path: (.+)\.go$
        text: ST1000
    paths:
      - trm/manager/mock
      - sql/mock
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - trm/manager/mock
      - sql/mock
