on:
  push:
    branches:
      - main
      - v1
  pull_request:
    branches:
      - main
      - v1
name: Test
env:
  GO_TARGET_VERSION: 1.19
jobs:
  # TODO add code coverage badge
  test:
    strategy:
      matrix:
        go-version:
          # - '1.10' doesn't have go module
          # - 1.11
          # - 1.12 doesn't have errors pkg
          # - 1.13 problem with recovery and defer
          # - 1.14
          # - 1.15
          - 1.16
          - 1.17
          - 1.18
          - 1.19
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod              # Module download cache
            ~/.cache/go-build         # Build cache (Linux)
            ~/Library/Caches/go-build # Build cache (Mac)
            '%LocalAppData%\go-build' # Build cache (Windows)
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Tests
        run: make test.coverage
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_TARGET_VERSION }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
